docs_dir: "docs"
site_name: Biblioteca do Campus
site_author: Grupo 2 - Curso de Back End em C# - Ada Tech - Mercado Eletrônico
copyright: |
  &copy; 2023 <a href="https://github.com/charles-serafim/AdaTech.BibliotecaDoCampus.git"  target="_blank" rel="noopener">Grupo 2 - Curso de Back End em C# - Ada Tech - Mercado Eletrônico</a>

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/git-alt
  # logo: "icon-640.png"
  # favicon: "favicon-640.png"
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light green
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: light green
      accent: indigo

nav:
  - Início: "index.md"

repo_url: https://github.com/charles-serafim/AdaTech.BibliotecaDoCampus
repo_name: AdaTech.BibliotecaDoCampus

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences